version: "3"
services:
    www:
        build: .
        ports: 
            - "9000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 9001:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
volumes:
    persistent: